version: '3'

services:
  app:
    build: build/php
    working_dir: /var/www/html
    command: php -S 0.0.0.0:8080 -t public
    environment:
      - dev=true
    ports:
      - 8080:8080
    volumes:
      - .:/var/www/html:consistent
      - /var/run/docker.sock:/var/run/docker.sock
